server:
  port: 8081

spring:
  application:
    name: springboot-employee-service-feign

security:
  basic:
    enabled: false # turn off securing our application endpoints

management:
  security:
    enabled: false